version: "3.7"
    
services:
  fs2od:
    # use image from a remote container registry
    image: registry.gitlab.ics.muni.cz:443/cryoem-dc/fs2od:latest
    # use locally built image
    # docker build -f Dockerfile -t fs2od .
    # image: fs2od
    restart: unless-stopped
    volumes:
      # share config.yaml from host to container
      - /home/someuser/fs2od/config.yaml:/opt/fs2od/config.yaml
      # make data directories accessible from host to container
      - /gpfs/volume1/test:/volumes/volume1/test
      #- /gpfs/volumeX/test:/volumes/volumeX/test
    environment:
      # If this variable is set to true, application will be periodically checking specifed directories
      # and import new subdirectories the Onedata. Set to "true" or "false" (with quotation marks).
      RUN_PERIODICALLY: "true"
      # Number of seconds between two checks
      REPEAT_TIME_PERIOD: 600 
