# Directories which will be watched by this application. These directories are periodically (or manulay) checked
# and in case of subdirectory is detected its processing are started. 
watchedDirectories:
  - "/volume/datasets" # this goes to /volume/datasets and scans all its subdirectories
  # examples with regex
  #- "/volume/datasets/*" # this goes to /volume/datasets and for all its subdirectories scans all subdirectories
  #- "/volume/user*/dataset" # this goes to /volume, in that finds any directory that satisfies regex user*, and scans all subdirectoriesof directory dataset

## Metadata settings
# Name of YAML files with metadata. Only if subdirectory contains one of specifed YAML files, it is proccesed by the application.
# To this file will be written attributes describing Onedata space.
metadataFiles:
  - "SPA.yml"

# Names of tags in metadata YAML file
metadataFileTags:
  onedata: Onedata2
  onezone: Onezone
  space: Space
  publicURL: PublicURL
  inviteToken: InviteToken
  deniedProviders: DeniedProviders
  removingTime: RemovingTime
  lastProgramRun: LastProgramRun

# separate fs2od metadata file
fs2odMetadataFile:
  enabled: False
  filename: ".fs2od"
  # if True, access info is stored to this file; if False, access info is stored to Original metadata file
  storeAccessInfo: True


# Name of institution importing datasets to Onedata
institutionName: MUNI ICS

# Prefix off all datasets (spaces, groups, tokens and storages)
datasetPrefix: ""

# Import attributes from metadata files to metadata stored by a Space in Onedata
importMetadata: False

# If enabled, parses metadata read from metadata (yaml) file to share. Renewed everytime when continuous import disabled
parseMetadataToShare: False

## Output detail level
# 0 - silent mode - nothing printed
# 1 - error
# 2 - error, warning
# 3 - error, warning, info
# 4 - error, warning, info, debug
# 5 - error, warning, info, debug, verbose (debug with extensive data prints)
verboseLevel: 3

## Test mode
# When test mode is allowed (set to True) all instances (spaces, tokens, groups, ...) are created with a given prefix,
# which value is set by testModePrefix. These instances with a prefix can be deleted in bulk by command:
# python3 test.py --remove_instances some_prefix
# In production set it to False.
testMode: True
testModePrefix: "test123_"

## Waiting
# It can take a while when Onedata compoments register changes which are made by calls of API. 
# Because of Onezone and Oneprovider in some case must exchange some information. E.g. if application do some changes 
# in Onezone, it must wait a while until it can manipulate with these changes on Oneprovider and vice versa. 
# Therefor there are a pauses between some function calls. You can set duration of waiting.
# 0 = don't sleep (only testing without Onedata)
# 1 = wait only a while (testing on small datasets)
# 2 = normal production value
sleepFactor: 1

## Setting of automatic continous import of files from POSIX filesystem to Onedata service
continousFileImport:
  # You can disable continous import of subdirectories. In this case content of direcotry is loaded only once at the time
  # when application come across the direcotry for the first time. If set to False, following atrributes aren't relevant.
  enabled: True
  # Name of file indicating that the subdirectory content can be modified. If directory contains this file (regardless to its content) ,
  # there will be set up a continous import of files from filesystem to Onedata service. If this file was removed, continous import 
  # is stopped. 
  runningFileName: ".running"
  # Time between two scans of filesystem by Oneprovider in seconds
  scanInterval: 10800
  # If set to True file modifications are detected. If set to False, only creations and deletions of files on
  # will be detected (files are treated as immutable).
  detectModifications: True
  # If set to True file deletions are detected. If set to False, files deletions aren't detected.
  detectDeletions: True

# Onedata POSIX like permissions which would be set to all directories and files
initialPOSIXlikePermissions: "0775"

# Parent group for dataspaces groups.
userGroupId: ""

# Implicit space size. It is size of space on Oneprovider after its creation. 
# Is should be set to great value (bigger than expected size of the bigest dataset directory). E.g. 10 TB = 10*2**40 = 10995116277760
implicitSpaceSize: 10995116277760

## AAI section
# Service user identifier
serviceUserId: ""

# Service group identifier
managerGroupId: ""

## DAREG - Datasets register
dareg:
  # Enable storing information about datasets to dareg
  enabled: False
  host: ""
  # Authorization token
  token: ""
  # ID of the fs2od instance in dareg
  origin_instance_pk: 1

# REST API access (hostnames and tokens) to Onedata services
# API token to Oneprovider must contain access to Onepanel in the same time
restAccess:
  onezone:
    host: ""
    apiToken: ""
  oneproviders:
    -
      host: ""
      apiToken: ""
      isPrimary: True # exactly one have to be primary
    -
      host: ""
      apiToken: ""
      storageIds: # all supporting providers must have storage IDs (at least one)
        - ""
        # - ""
    #-
    #  host: ""
    #  apiToken: ""
    #  storageIds:
    #    - ""
    #    # - ""

messaging:
  credentials:
    email:
      # If disabled, fields will not be checked
      enabled: false
      # SMTP server which will receive emails to send further
      smtpServer: ""
      # If no port is provided, and encryption method is correct,
      # default values are 465 for "TLS" and "SSL", 587 for "STARTTLS" and 25 for "ANY"
      smtpPort: 0
      # If no login or password provided, tries to send emails without authentication
      login: ""
      password: ""
      # Possible values are "SSL", "TLS", "STARTTLS", "ANY", behavior of "SSL" is the same as of "TLS"
      # If wrong keyword is set and email enabled, app will crash
      encryptionMethod: ""
      # From field value, it can be clear email address, or text in format "Name Surname <user@mail.tld>"
      messageSender: ""

  email:
    # Same format as messageSender
    to:
      - ""
      - ""
    # Sends email when given timestamp is reached, same format as timeUntilRemoved
    timeBeforeAction:
      - 1m
      - 7d
      - 1d
      - 2h
    # ISO 639-1 country code, case (upper-/lower-) is ignored, default is en
    # if choosing document to send, first it will try to find its translated version, then original
    language: "SK"

## Setting data replication between possible spaces supporters
dataReplication:
  #
  enabled: true
  # Number of servers to which it will be replicated, source included
  numberOfReplicas: 2
  # Time to wait from finding out that must remove from primary Oneprovider until actual deletion is processed
  # Possible time descriptors are: y for years, m for months, d for days, h for hours
  # Numbers concatenate with decorators, between two decorator types have to be spaces
  # Everything will be summed up. Month has 30 days.
  # Special values: never, now and transfers - BE AWARE OF VALUE `now`, IT WILL REMOVE FILES IMMEDIATELY!!!
  # Value transfers is only for system, never you ever do change to transfers, you can lose your data forever
  # without even noticing
  # Examples: "7d 5h", "10y", "2m", "3h 5h" (will be summed up to 8 hours)
  timeUntilRemoved: "7d"
  # if remove from filesystem is True, when time is up for disconnecting actual provider from the space support,
  # it will physically remove data from its filesystem. This operation is irreversible and you can lose your data.
  removeFromFilesystem: false
